packages:
  - name: subinfo-update-checker
    environment:
      GITHUB_ACCESS_TOKEN: "${GITHUB_ACCESS_TOKEN}"
      SPACES_KEY: "${SPACES_KEY}"
      SPACES_SECRET: "${SPACES_SECRET}"
      SPACES_BUCKET: "${SPACES_BUCKET}"
    actions:
      - name: john-oliver
        runtime: "nodejs:default"
        web: false
        main: ''
        limits:
          timeout: 900000
        triggers:
          - name: run-every-hour
            sourceType: scheduler
            sourceDetails:
              cron: "30 * * * *"
