packages:
  - name: subinfo-update-checker
    functions:
      - name: john-oliver
        runtime: "nodejs:default"
        triggers:
          - name: run-every-hour
            sourceType: scheduler
            sourceDetails:
              cron: "0 * * * *"
