name: Deploy to DigitalOcean Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Init serverless functionality for doctl
        run: |
          doctl serverless install
          doctl serverless connect
      
      - name: Set up .env
        run: |
          touch .env
          echo "GITHUB_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}" >> .env
          echo "SPACES_KEY=${{ secrets.SPACES_KEY }}" >> .env
          echo "SPACES_SECRET=${{ secrets.SPACES_SECRET }}" >> .env
          echo "SPACES_BUCKET=${{ secrets.SPACES_BUCKET }}" >> .env
      
      - name: Deploy to DO Functions
        run: doctl serverless deploy
